/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourceTokenRouteImport } from './routes/source.$token'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as IntakeLinksNewRouteImport } from './routes/intake-links.new'
import { Route as CertificatesPublicIdRouteImport } from './routes/certificates.$publicId'
import { Route as ApiJobsJobIdStreamRouteImport } from './routes/api.jobs.$jobId.stream'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceTokenRoute = SourceTokenRouteImport.update({
  id: '/source/$token',
  path: '/source/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeLinksNewRoute = IntakeLinksNewRouteImport.update({
  id: '/intake-links/new',
  path: '/intake-links/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesPublicIdRoute = CertificatesPublicIdRouteImport.update({
  id: '/certificates/$publicId',
  path: '/certificates/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdStreamRoute = ApiJobsJobIdStreamRouteImport.update({
  id: '/api/jobs/$jobId/stream',
  path: '/api/jobs/$jobId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/methodology': typeof MethodologyRoute
  '/certificates/$publicId': typeof CertificatesPublicIdRoute
  '/intake-links/new': typeof IntakeLinksNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/source/$token': typeof SourceTokenRoute
  '/api/jobs/$jobId/stream': typeof ApiJobsJobIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/methodology': typeof MethodologyRoute
  '/certificates/$publicId': typeof CertificatesPublicIdRoute
  '/intake-links/new': typeof IntakeLinksNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/source/$token': typeof SourceTokenRoute
  '/api/jobs/$jobId/stream': typeof ApiJobsJobIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/methodology': typeof MethodologyRoute
  '/certificates/$publicId': typeof CertificatesPublicIdRoute
  '/intake-links/new': typeof IntakeLinksNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/source/$token': typeof SourceTokenRoute
  '/api/jobs/$jobId/stream': typeof ApiJobsJobIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/methodology'
    | '/certificates/$publicId'
    | '/intake-links/new'
    | '/jobs/$jobId'
    | '/source/$token'
    | '/api/jobs/$jobId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/methodology'
    | '/certificates/$publicId'
    | '/intake-links/new'
    | '/jobs/$jobId'
    | '/source/$token'
    | '/api/jobs/$jobId/stream'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/methodology'
    | '/certificates/$publicId'
    | '/intake-links/new'
    | '/jobs/$jobId'
    | '/source/$token'
    | '/api/jobs/$jobId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MethodologyRoute: typeof MethodologyRoute
  CertificatesPublicIdRoute: typeof CertificatesPublicIdRoute
  IntakeLinksNewRoute: typeof IntakeLinksNewRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  SourceTokenRoute: typeof SourceTokenRoute
  ApiJobsJobIdStreamRoute: typeof ApiJobsJobIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source/$token': {
      id: '/source/$token'
      path: '/source/$token'
      fullPath: '/source/$token'
      preLoaderRoute: typeof SourceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake-links/new': {
      id: '/intake-links/new'
      path: '/intake-links/new'
      fullPath: '/intake-links/new'
      preLoaderRoute: typeof IntakeLinksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$publicId': {
      id: '/certificates/$publicId'
      path: '/certificates/$publicId'
      fullPath: '/certificates/$publicId'
      preLoaderRoute: typeof CertificatesPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/stream': {
      id: '/api/jobs/$jobId/stream'
      path: '/api/jobs/$jobId/stream'
      fullPath: '/api/jobs/$jobId/stream'
      preLoaderRoute: typeof ApiJobsJobIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MethodologyRoute: MethodologyRoute,
  CertificatesPublicIdRoute: CertificatesPublicIdRoute,
  IntakeLinksNewRoute: IntakeLinksNewRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  SourceTokenRoute: SourceTokenRoute,
  ApiJobsJobIdStreamRoute: ApiJobsJobIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
